version: "3"
services:
  app:
    image: getdtk/graph-example1-app
    container_name: app
    build: .
    environment:
    - PORT=8080
    - DB_HOST=<REDIS_HOST>
    - DB_PORT=<REDIS_PORT>
    - DB_PASSWORD=<REDIS_PASSWORD>
    ports:
      - "8080:8080"
