---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    app: node
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31112
  selector:
    app: node
