---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    app: node
spec:
  type: NodePort
  ports:
  - port: 8081 # Change from 8080 to 8081
    targetPort: 8080
    nodePort: 31112
  selector:
    svc: node-app-svc2 # Change from node-app-svc to node-app-svc2 to provoke reasoning mechanism (service doesn't match pods now)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  labels:
    app: node
spec:
  selector:
    matchLabels:
      dep: node-app-dep
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
  replicas: 3 # Change from 1 to 3
  template:
    metadata:
      labels:
        svc: node-app-svc
        dep: node-app-dep
    spec:
      containers:
      - name: node
        image: getdtk/graph-example1-app:v2 # Change from getdtk/graph-example1-app to getdtk/graph-example1-app:v2
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: '8080'
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: node-app-secret
              key: db_password
        - name: DB_HOST
          value: my-release-redis-master
        - name: DB_PORT
          value: '6379'
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "400Mi" # Change from 200Mi to 400Mi
            cpu: "400m" # Change from 200m to 400m