---
apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  labels:
    app: node
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31112
  selector:
    app: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
  labels:
    app: node
spec:
  selector:
    matchLabels:
      app: node
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 1 # max number of pods that can be created over the desired number of pods
     maxUnavailable: 0 # max number of pods that can be unavailable during rolling update
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: getdtk/graph-example1-app
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: '8080'
        - name: DB_PASSWORD
          value: password
        - name: DB_HOST
          value: my-release-redis-master
        - name: DB_PORT
          value: '6379'
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
